export interface Tree {
  id: string
  type: "type1" | "type2" | "type3"
  title: string
  description: string
  persona: string
  impact: string
  techStack: string[]
  aiFunctionality: string
  implementedBy: string
  scale: string
  geography: string
  insights: string
}

export const mockTrees: Tree[] = [
  {
    id: "1",
    type: "type1",
    title: "Customer Analytics Engine",
    description:
      "Advanced analytics platform that processes customer behavior data to provide actionable insights for business growth.",
    persona: "Data Scientists, Business Analysts, Marketing Teams",
    impact: "Increased customer retention by 35% and improved marketing ROI by 50%",
    techStack: ["Python", "Apache Spark", "TensorFlow", "PostgreSQL", "React"],
    aiFunctionality:
      "Machine learning models for customer segmentation, churn prediction, and lifetime value calculation",
    implementedBy: "Enterprise Analytics Team",
    scale: "10M+ customer records, 1M+ daily queries",
    geography: "North America, Europe",
    insights:
      "Real-time analytics reduced decision-making time from days to hours, enabling rapid response to market changes.",
  },
  {
    id: "2",
    type: "type2",
    title: "Automated Workflow Optimizer",
    description: "Intelligent automation system that streamlines business processes and reduces manual intervention.",
    persona: "Operations Managers, Process Engineers, IT Teams",
    impact: "Reduced processing time by 60% and eliminated 80% of manual errors",
    techStack: ["Node.js", "RPA Tools", "MongoDB", "Docker", "Kubernetes"],
    aiFunctionality: "Process mining algorithms and intelligent task routing based on workload and priority",
    implementedBy: "Automation Center of Excellence",
    scale: "500+ automated processes, 50K+ daily transactions",
    geography: "Global deployment across 15 countries",
    insights: "Automation freed up 40% of employee time for strategic work, significantly improving job satisfaction.",
  },
  {
    id: "3",
    type: "type3",
    title: "Predictive Maintenance AI",
    description:
      "AI-powered system that predicts equipment failures before they occur, optimizing maintenance schedules.",
    persona: "Maintenance Engineers, Plant Managers, Operations Teams",
    impact: "Reduced unplanned downtime by 45% and maintenance costs by 30%",
    techStack: ["Python", "IoT Sensors", "Azure ML", "Time Series DB", "Power BI"],
    aiFunctionality: "Deep learning models for anomaly detection and failure prediction using sensor data",
    implementedBy: "Industrial IoT Team",
    scale: "1000+ connected machines, 100M+ sensor readings daily",
    geography: "Manufacturing facilities in Asia-Pacific",
    insights:
      "Predictive approach shifted maintenance from reactive to proactive, extending equipment lifespan by 25%.",
  },
  {
    id: "4",
    type: "type1",
    title: "Sales Performance Dashboard",
    description: "Comprehensive analytics dashboard providing real-time insights into sales performance and trends.",
    persona: "Sales Managers, Regional Directors, C-Suite Executives",
    impact: "Improved sales forecasting accuracy by 40% and increased team productivity by 25%",
    techStack: ["Tableau", "Snowflake", "Python", "REST APIs", "AWS"],
    aiFunctionality: "Predictive analytics for sales forecasting and territory optimization",
    implementedBy: "Business Intelligence Team",
    scale: "500+ sales reps, 10K+ daily updates",
    geography: "Americas and EMEA regions",
    insights:
      "Visual analytics enabled data-driven decisions, resulting in more accurate quota setting and territory planning.",
  },
  {
    id: "5",
    type: "type2",
    title: "Document Processing Bot",
    description:
      "Automated system for processing, categorizing, and extracting information from various document types.",
    persona: "Administrative Staff, Legal Teams, Compliance Officers",
    impact: "Processed 90% of documents automatically, reducing processing time from hours to minutes",
    techStack: ["OCR Technology", "NLP Libraries", "Azure Cognitive Services", "SharePoint", "Power Automate"],
    aiFunctionality: "Natural language processing for document classification and intelligent data extraction",
    implementedBy: "Digital Transformation Team",
    scale: "10K+ documents monthly, 95% accuracy rate",
    geography: "Corporate headquarters and regional offices",
    insights: "Automation eliminated document backlogs and improved compliance reporting accuracy significantly.",
  },
  {
    id: "6",
    type: "type3",
    title: "Intelligent Chatbot Assistant",
    description: "AI-powered conversational agent that provides 24/7 customer support and handles complex queries.",
    persona: "Customer Service Representatives, End Customers, Support Managers",
    impact: "Resolved 70% of queries automatically, improved customer satisfaction by 35%",
    techStack: ["Dialogflow", "Node.js", "MongoDB", "WebSocket", "Google Cloud"],
    aiFunctionality: "Natural language understanding, sentiment analysis, and contextual conversation management",
    implementedBy: "Customer Experience Team",
    scale: "50K+ monthly conversations, 24/7 availability",
    geography: "Global customer base across all time zones",
    insights:
      "AI assistant reduced average response time from 4 hours to 30 seconds, dramatically improving customer experience.",
  },
  {
    id: "7",
    type: "type1",
    title: "Market Intelligence Platform",
    description: "Advanced analytics platform that monitors market trends, competitor activities, and consumer sentiment.",
    persona: "Market Researchers, Strategic Planners, Product Managers",
    impact: "Identified market opportunities 3 months earlier, leading to 20% faster product launches",
    techStack: ["Elasticsearch", "Kafka", "Spark Streaming", "D3.js", "AWS Lambda"],
    aiFunctionality: "Sentiment analysis, trend detection, and competitive intelligence using web scraping and social media monitoring",
    implementedBy: "Market Intelligence Unit",
    scale: "1M+ data points daily, 100+ market segments tracked",
    geography: "Global market coverage with focus on key regions",
    insights: "Real-time market intelligence enabled proactive strategy adjustments and competitive advantage.",
  },
  {
    id: "8",
    type: "type2",
    title: "Supply Chain Optimizer",
    description: "Automated system that optimizes inventory levels, supplier selection, and logistics routing.",
    persona: "Supply Chain Managers, Procurement Teams, Logistics Coordinators",
    impact: "Reduced inventory costs by 25% while improving delivery times by 30%",
    techStack: ["Optimization Algorithms", "SAP Integration", "Python", "PostgreSQL", "Tableau"],
    aiFunctionality: "Machine learning for demand forecasting and genetic algorithms for route optimization",
    implementedBy: "Supply Chain Excellence Team",
    scale: "500+ suppliers, 10K+ SKUs managed",
    geography: "Multi-regional supply network across 3 continents",
    insights: "Optimization algorithms balanced cost and service levels, creating a more resilient supply chain.",
  },
  {
    id: "9",
    type: "type3",
    title: "Fraud Detection System",
    description: "Real-time AI system that identifies and prevents fraudulent transactions and activities.",
    persona: "Risk Analysts, Fraud Investigators, Compliance Teams",
    impact: "Detected 95% of fraud attempts with only 2% false positive rate",
    techStack: ["Apache Kafka", "TensorFlow", "Redis", "Elasticsearch", "Grafana"],
    aiFunctionality: "Ensemble machine learning models with real-time anomaly detection and behavioral analysis",
    implementedBy: "Risk Management Team",
    scale: "1M+ transactions analyzed daily, sub-second response time",
    geography: "Global financial operations",
    insights: "AI-driven fraud detection saved millions in potential losses while maintaining smooth customer experience.",
  },
  {
    id: "10",
    type: "type1",
    title: "Employee Performance Analytics",
    description: "Comprehensive platform analyzing employee performance, engagement, and career development patterns.",
    persona: "HR Managers, Team Leaders, Organizational Development Specialists",
    impact: "Improved employee retention by 40% and identified high-potential talent 6 months earlier",
    techStack: ["R", "Shiny", "MySQL", "LDAP Integration", "Power BI"],
    aiFunctionality: "Predictive modeling for performance trends and career path recommendations",
    implementedBy: "People Analytics Team",
    scale: "5K+ employees tracked, quarterly performance cycles",
    geography: "Corporate offices in North America and Europe",
    insights: "Data-driven insights transformed talent management from intuition-based to evidence-based decisions.",
  },
  {
    id: "11",
    type: "type2",
    title: "Invoice Processing Automation",
    description: "End-to-end automated system for invoice receipt, validation, approval, and payment processing.",
    persona: "Accounts Payable Teams, Finance Managers, Vendors",
    impact: "Reduced invoice processing time by 80% and improved accuracy to 99.5%",
    techStack: ["OCR Technology", "Workflow Engine", "SAP Integration", "Email APIs", "Azure Functions"],
    aiFunctionality: "Intelligent document processing with automatic data extraction and validation rules",
    implementedBy: "Finance Automation Team",
    scale: "20K+ invoices monthly, multi-currency support",
    geography: "Global finance operations across all subsidiaries",
    insights: "Automation eliminated manual data entry errors and accelerated vendor payment cycles significantly.",
  },
  {
    id: "12",
    type: "type3",
    title: "Content Recommendation Engine",
    description: "AI-powered system that personalizes content recommendations based on user behavior and preferences.",
    persona: "Content Managers, Marketing Teams, End Users",
    impact: "Increased user engagement by 60% and content consumption by 45%",
    techStack: ["Collaborative Filtering", "Apache Spark", "Cassandra", "Kafka", "React Native"],
    aiFunctionality: "Deep learning recommendation algorithms with real-time personalization and A/B testing",
    implementedBy: "Product Personalization Team",
    scale: "2M+ active users, 100K+ content items",
    geography: "Global user base with localized content",
    insights: "Personalized recommendations created more engaging user experiences and increased platform stickiness.",
  },
  {
    id: "13",
    type: "type1",
    title: "Social Media Sentiment Analyzer",
    description: "Real-time analysis of social media sentiment and brand perception.",
    persona: "Marketing Teams, Brand Managers, Social Media Analysts",
    impact: "Improved brand sentiment by 40% and identified 2x more engagement opportunities",
    techStack: ["Python", "NLTK", "Twitter API", "MongoDB", "React"],
    aiFunctionality: "Sentiment analysis and trend detection",
    implementedBy: "Digital Marketing Team",
    scale: "1M+ social media posts analyzed daily",
    geography: "Global social media platforms",
    insights: "AI identified emerging brand issues before they became crises.",
  },
  {
    id: "14",
    type: "type2",
    title: "Email Response Automation",
    description: "Smart system that automatically categorizes and responds to customer emails.",
    persona: "Customer Service Teams, Support Staff, Office Administrators",
    impact: "Reduced email response time by 85% and improved customer satisfaction by 45%",
    techStack: ["Gmail API", "Python", "NLP", "Azure Functions", "Power Automate"],
    aiFunctionality: "Email classification and automated response generation",
    implementedBy: "Customer Support Team",
    scale: "5000+ emails processed daily",
    geography: "Global support centers",
    insights: "Automation freed up 200+ hours of staff time weekly for complex queries.",
  },
  {
    id: "15",
    type: "type3",
    title: "Smart Recruitment System",
    description: "AI-powered platform that screens resumes and matches candidates to job requirements.",
    persona: "HR Teams, Recruiters, Hiring Managers",
    impact: "Reduced hiring time by 50% and improved candidate quality by 40%",
    techStack: ["Python", "NLP", "Azure ML", "React", "MongoDB"],
    aiFunctionality: "Resume parsing and candidate matching",
    implementedBy: "HR Technology Team",
    scale: "1000+ applications processed monthly",
    geography: "Global recruitment",
    insights: "AI system identified 30% more qualified candidates than traditional screening.",
  }
]
